Repository googleapis/java-monitoring, pull requests merged in 2020-08, with the labels that each got.

#214 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#219 chore: clean up dependency version managed by self
  google-cloud-monitoring/pom.xml
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
Labels: automerge, cla: yes

#218 chore: regenerate common templates
  .kokoro/dependencies.sh
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#220 chore: regenerate README versions
  README.md
  synth.metadata
Labels: cla: yes, context: none

#224 chore: fix sample snippet versions
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: none

#226 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#230 deps: fix scope for google-auth-library-oauth2-http
  google-cloud-monitoring/pom.xml
Labels: cla: yes

#227 samples: migrate samples from GoogleCloudPlatform/java-docs-samples monitoring/cloud-client
  samples/snippets/src/main/java/com/example/monitoring/Snippets.java
  samples/snippets/src/test/java/com/example/monitoring/SnippetsIT.java
Labels: cla: yes

#234 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#242 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#243 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: monitoring, cla: yes, context: full

#244 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
