Repository googleapis/java-monitoring, pull requests merged in 2020-10, with the labels that each got.

#290 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: api: monitoring, cla: yes, context: full

#293 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#281 chore: remove unused dependency
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: api: monitoring, cla: yes, type: cleanup

#300 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#301 chore: regenerate common templates
  .github/workflows/approve-readme.yaml
  .kokoro/build.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#307 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#316 chore: regenerate common templates
  .github/snippet-bot.yml
  renovate.json
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#314 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#318 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#319 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#322 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#320 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#324 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#325 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#328 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#329 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
