Repository googleapis/java-monitoring, pull requests merged in 2020-12, with the labels that each got.

#366 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#367 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#369 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#282 test(samples): add retry setting in getUptimeCheckConfig for fix build
  samples/snippets/src/main/java/com/example/monitoring/UptimeSample.java
Labels: api: monitoring, cla: yes, samples

#373 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#375 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#385 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#386 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#387 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#389 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: monitoring, cla: yes, context: full
