Repository googleapis/java-monitoring, pull requests merged in 2020-09, with the labels that each got.

#256 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: monitoring, cla: yes, context: full

#257 chore: regenerate README
  README.md
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: none

#273 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#271 fix: remove duplicate monitor client classes
  src/main/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClient.java
  src/main/java/com/google/cloud/monitoring/v3/AlertPolicyServiceSettings.java
  src/main/java/com/google/cloud/monitoring/v3/GroupServiceClient.java
  src/main/java/com/google/cloud/monitoring/v3/GroupServiceSettings.java
  src/main/java/com/google/cloud/monitoring/v3/MetricServiceClient.java
  src/main/java/com/google/cloud/monitoring/v3/MetricServiceSettings.java
  src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceSettings.java
  src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClient.java
  src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceSettings.java
  src/main/java/com/google/cloud/monitoring/v3/package-info.java
  src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStubSettings.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStubSettings.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcAlertPolicyServiceCallableFactory.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcAlertPolicyServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcGroupServiceCallableFactory.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcGroupServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcMetricServiceCallableFactory.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcMetricServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceCallableFactory.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcUptimeCheckServiceCallableFactory.java
  src/main/java/com/google/cloud/monitoring/v3/stub/GrpcUptimeCheckServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStubSettings.java
  src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStubSettings.java
  src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStub.java
  src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStubSettings.java
  src/test/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClientTest.java
  src/test/java/com/google/cloud/monitoring/v3/GroupServiceClientTest.java
  src/test/java/com/google/cloud/monitoring/v3/MetricServiceClientTest.java
  src/test/java/com/google/cloud/monitoring/v3/MetricServiceSmokeTest.java
  src/test/java/com/google/cloud/monitoring/v3/MockAlertPolicyService.java
  src/test/java/com/google/cloud/monitoring/v3/MockAlertPolicyServiceImpl.java
  src/test/java/com/google/cloud/monitoring/v3/MockGroupService.java
  src/test/java/com/google/cloud/monitoring/v3/MockGroupServiceImpl.java
  src/test/java/com/google/cloud/monitoring/v3/MockMetricService.java
  src/test/java/com/google/cloud/monitoring/v3/MockMetricServiceImpl.java
  src/test/java/com/google/cloud/monitoring/v3/MockNotificationChannelService.java
  src/test/java/com/google/cloud/monitoring/v3/MockNotificationChannelServiceImpl.java
  src/test/java/com/google/cloud/monitoring/v3/MockUptimeCheckService.java
  src/test/java/com/google/cloud/monitoring/v3/MockUptimeCheckServiceImpl.java
  src/test/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClientTest.java
  src/test/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClientTest.java
Labels: api: monitoring, cla: yes

#275 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: monitoring, automerge, cla: yes

#277 chore: regenerate common templates
  .github/workflows/auto-release.yaml
  README.md
  synth.metadata
Labels: api: monitoring, cla: yes, context: partial

#283 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#286 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
