Repository googleapis/java-monitoring, pull requests merged in 2021-02, with the labels that each got.

#388 docs(samples): fix NPE in DeleteMetricDescriptorIT#testDeleteMetricDe…
  samples/snippets/src/test/java/com/example/monitoring/CreateAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/CreateMetricDescriptorIT.java
  samples/snippets/src/test/java/com/example/monitoring/DeleteAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/DeleteMetricDescriptorIT.java
  samples/snippets/src/test/java/com/example/monitoring/DeleteNotificationChannelIT.java
  samples/snippets/src/test/java/com/example/monitoring/EnableDisableAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/GetAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/GetMonitoredResourceIT.java
  samples/snippets/src/test/java/com/example/monitoring/ListAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/ListMetricDescriptorIT.java
  samples/snippets/src/test/java/com/example/monitoring/ListMonitoredResourcesIT.java
  samples/snippets/src/test/java/com/example/monitoring/QuickstartSampleIT.java
  samples/snippets/src/test/java/com/example/monitoring/TimeSeriesIT.java
  samples/snippets/src/test/java/com/example/monitoring/UpdateAlertPolicyIT.java
  samples/snippets/src/test/java/com/example/monitoring/UptimeIT.java
Labels: api: monitoring, cla: yes, samples

#411 chore: Re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: partial

#416 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#406 chore: Re-generated to pick up changes from googleapis
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/GroupServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/MetricServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/ServiceMonitoringServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/AlertPolicyServiceStubSettings.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GroupServiceStubSettings.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcAlertPolicyServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcGroupServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcMetricServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcServiceMonitoringServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcUptimeCheckServiceCallableFactory.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/MetricServiceStubSettings.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/NotificationChannelServiceStubSettings.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/ServiceMonitoringServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/ServiceMonitoringServiceStubSettings.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/UptimeCheckServiceStubSettings.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClientTest.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MetricServiceClientTest.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/ServiceMonitoringServiceClientTest.java
  proto-google-cloud-monitoring-v3/src/main/java/com/google/monitoring/v3/ServiceTier.java
  synth.metadata
  synth.py
Labels: api: monitoring, automerge, cla: yes, context: partial

#418 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: partial

#419 docs: generate sample code in the Java microgenerator
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/AlertPolicyServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/GroupServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/MetricServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/ServiceMonitoringServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/UptimeCheckServiceClient.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/package-info.java
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full, samples

#421 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#423 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#422 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#426 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#425 chore: update gapic-generator-java to 0.0.20
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcAlertPolicyServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcGroupServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcMetricServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcNotificationChannelServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcServiceMonitoringServiceStub.java
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/stub/GrpcUptimeCheckServiceStub.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MetricServiceClientTest.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockAlertPolicyServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockGroupServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockMetricServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockNotificationChannelServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockServiceMonitoringServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/MockUptimeCheckServiceImpl.java
  google-cloud-monitoring/src/test/java/com/google/cloud/monitoring/v3/NotificationChannelServiceClientTest.java
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#427 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#429 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#430 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#433 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/v3/gapic_metadata.json
  synth.metadata
Labels: api: monitoring, automerge, cla: yes, context: full

#435 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#436 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#439 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#441 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes

#446 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: monitoring, automerge, cla: yes
